/* Generated by scripts/build-content-packs.mjs. */
import type { ImageSource } from 'expo-image';

export const exerciseGifs: Record<string, ImageSource> = {
  'offline-025': require('../../assets/exercises/core/offline-025.webp'),
  'offline-117': require('../../assets/exercises/core/offline-117.webp'),
  'offline-187': require('../../assets/exercises/core/offline-187.webp'),
  'offline-198': require('../../assets/exercises/core/offline-198.webp'),
  'offline-225': require('../../assets/exercises/core/offline-225.webp'),
  'offline-241': require('../../assets/exercises/core/offline-241.webp'),
  'offline-307': require('../../assets/exercises/core/offline-307.webp'),
  'offline-362': require('../../assets/exercises/core/offline-362.webp'),
  'offline-379': require('../../assets/exercises/core/offline-379.webp'),
  'offline-411': require('../../assets/exercises/core/offline-411.webp'),
  'offline-429': require('../../assets/exercises/core/offline-429.webp'),
  'offline-441': require('../../assets/exercises/core/offline-441.webp'),
  'offline-447': require('../../assets/exercises/core/offline-447.webp'),
  'offline-473': require('../../assets/exercises/core/offline-473.webp'),
  'offline-495': require('../../assets/exercises/core/offline-495.webp'),
  'offline-516': require('../../assets/exercises/core/offline-516.webp'),
  'offline-573': require('../../assets/exercises/core/offline-573.webp'),
  'offline-574': require('../../assets/exercises/core/offline-574.webp'),
  'offline-672': require('../../assets/exercises/core/offline-672.webp'),
  'offline-729': require('../../assets/exercises/core/offline-729.webp'),
  'offline-761': require('../../assets/exercises/core/offline-761.webp'),
  'offline-869': require('../../assets/exercises/core/offline-869.webp'),
};
